# Generated by Django 4.2.10 on 2024-02-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='first',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=55)),
                ('Last_name', models.CharField(max_length=55)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
