# Generated by Django 4.2.10 on 2024-02-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='Last_name',
            field=models.CharField(max_length=55, null='True'),
        ),
    ]
