# Generated by Django 4.2.10 on 2024-02-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0002_alter_first_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='first',
            new_name='your_model',
        ),
    ]
